# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo apt-get install wine64
    - run: npm ci
    - run: npm run ts-build
    - run: npm run build-win32
    - run: ls
    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
          # Artifact name
          name: build-windows-x64
          # A file, directory or wildcard pattern that describes what to upload
          path: build-win32-x64
          if-no-files-found: warn
          # Duration after which artifact will expire in days. 0 means using default retention.
          retention-days: 31
